### ISSUE TITLE
Both of the userdata queries return 2% for all boosts

### ISSUE THREAD

**Issue by xarimus** [edvordo/roa-apis#2]
Both of the userdata queries return 2% for all boosts.

Example from users-active:
`            "critical_hit_chance": {
                "trains": 75000,
                "value": "2%",
                "rank": 151`

Example from users:
`            "critical_hit_chance": {
                "trains": 10000,
                "value": "2%",
                "rank": 563`

**Comment by edvordo** [comment]
Hey, thank you for reporting this issue!

I checked the endpoints and while yes, all `critical_hit_chance` entries seem to state just 2%, this very much looks like an error on the games' side, as 2% is unlikely to be the correct info regardless of how much training has given person done.

But even if 2% was correct, this repository stores only exemplary data and the value is still a string value ending with a percent sign, so at the end of the day it doesn't matter whether it's 2% or x%, therefore I will not be making any changes.
